# The app.yaml configuration file for a simple application, using the Python 3.9 runtime environment

application: myGaeApp
version: 1
runtime: python39
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.application
